config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "rooms#index"

  resources :rooms, only: [:new, :create, :destroy] do
    member do
      patch 'habit_change'
      post 'habit_add'
    end
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:index]
  resources :habits, only: [:new, :create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habit.rb
class Habit < ApplicationRecord
  validates :title, presence: true 
  validates :item1, presence: true 

  belongs_to :user
  has_many :room_habits, dependent: :destroy
  has_many :rooms, through: :room_habits

end

app/models/message.rb
class Message < ApplicationRecord
  attr_accessor :habit_id
  validates :comment, presence: true 

  belongs_to :room
  belongs_to :user

end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true 

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :room_habits, dependent: :destroy
  has_many :habits, through: :room_habits

end

app/models/room_habit.rb
class RoomHabit < ApplicationRecord
  belongs_to :room
  belongs_to :habit

end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true 

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :habits

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:edit, :update, :destroy]
  def new
    @habit = Habit.new
    # @room = Room.find(params[:room_id])
  end
  def create
    @habit = Habit.new(habit_params)
    if @habit.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @habit.update(habit_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @habit.destroy
    redirect_to users_path
  end
  private
  def habit_params
    params.require(:habit).permit(:title, :item1, :item2, :item3, :item4, :item5).merge(user_id: current_user.id)
  end

  def set_habit
    @habit = Habit.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
    @habits = @room.habits
    @my_habits = Habit.where(user_id: current_user.id)
    @not_habits = not_set_habit
  end 
  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
    redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end
  private
  def message_params
    params.require(:message).permit(:comment).merge(user_id: current_user.id)
  end
  def not_set_habit
    if @room.user_ids.length > @habits.length
      habits = []
        @habits.each do |habit|
          habits << habit.user_id
        end
        not_habit = []
        @room.user_ids.each do |user|
           if habits.include?(user)
           elsif 
            not_habit << User.find(user)
           end
        end
        return(not_habit)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:destroy]

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.user_ids == [current_user.id]
      render :new
    elsif  @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  def habit_change
    @room = Room.find(params[:id])  
    @room_habits = RoomHabit.all
    @room_habits.each_with_index do |room_habit|
      if room_habit.room_id == @room.id && room_habit.habit_id == params[:habit_id].to_i
        @room_habit = RoomHabit.find(room_habit.id)
        @room_habit[:habit_id] = params[:select_habit_id]
        @room_habit.save
        redirect_to "/rooms/#{@room.id}/messages"
      end
    end
  end

  def habit_add
    @room = params[:id].to_i 
    @habit = params[:select_habit_id].to_i
    roomhabit_params = {}
    roomhabit_params[:room_id] = @room
    roomhabit_params[:habit_id] = @habit
    RoomHabit.create(roomhabit_params)
    redirect_to "/rooms/#{@room}/messages"
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @habits = Habit.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/edit.html.erb
<%# CSS・・・assets/stylesheets/inputform.css %>
<%= render "share/header" %>
<div class='main_account'>
  <div>
    <div class='room-error'>
    </div>
    <div class='detail_new_habit'>
      <div class='new_room_side'>
        <div class='room_create'>
        リスト登録
        </div>
          <div class='habit_resist_explantion'>
          項目を1つ以上登録してください
          </div>
      </div>
      <div class='new_room_main'>
        <%= form_with model: @habit, local: true do |f| %>
        <div class='room_input'>
          <div class="field">
            <div>タイトル</div>
            <%= f.text_field :title, autofocus: true, autocomplete: "name", placeholder: "リストのタイトルを入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目①</div>
            <%= f.text_field :item1, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目②</div>
            <%= f.text_field :item2, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目③</div>
            <%= f.text_field :item3, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目④</div>
            <%= f.text_field :item4, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目⑤</div>
            <%= f.text_field :item5, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
          <%= f.submit "登録" ,class: "room_btn" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/habits/new.html.erb
<%# CSS・・・assets/stylesheets/inputform.css %>
<%= render "share/header" %>
<div class='main_account'>
  <div>
    <div class='room-error'>
    </div>
    <div class='detail_new_habit'>
      <div class='new_room_side'>
        <div class='room_create'>
        リスト登録
        </div>
          <div class='habit_resist_explantion'>
          項目を1つ以上登録してください
          </div>
      </div>
      <div class='new_room_main'>
        <%= form_with model: @habit, local: true do |f| %>
        <div class='room_input'>
          <div class="field">
            <div>タイトル</div>
            <%= f.text_field :title, autofocus: true, autocomplete: "name", placeholder: "リストのタイトルを入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目①</div>
            <%= f.text_field :item1, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目②</div>
            <%= f.text_field :item2, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目③</div>
            <%= f.text_field :item3, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目④</div>
            <%= f.text_field :item4, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
        <div class='room_input'>
          <div class="field">
            <div>項目⑤</div>
            <%= f.text_field :item5, autocomplete: "name", placeholder: "項目を入力してください",class: "input_form" %>
          </div>
        </div>
          <%= f.submit "登録" ,class: "room_btn" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>習慣化応援アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<% if message.user.id == current_user.id %>
<div class='left_message_main'>
<% else %>
<div class='right_message_main'>
<% end %>
  <div class='message_border'>
    <div class='message_main_top'>
      <div class='message_name'>
      <%= message.user.nickname %>
      </div>
      <div class='message_date'>
      <%= l message.created_at %>
      </div>
    </div>
    <div class='message_comment'>
    <%= message.comment %>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<%# CSS・・・assets/stylesheets/message.css %>
<%= render "share/header" %>
<div class='message_top'>

  <% @habits.each do |habit| %>
  <div class='room_habit_list'>
      <div class='room_list_bottom'>
        <div class='message_user_name'>
        <%= habit.user.nickname %>
        </div>
      </div>
      <div class='habit_list' >
      <%= form_with model: @room, url: habit_change_room_path(@room.id, habit_id: habit.id), method: :patch, local: true do |f| %>
        <div class='habit_list_top'>
          <div class='habit_list_left_btn'>
            <div class='habit_title'>
            <% if current_user.id == habit.user_id %>
            <select name="select_habit_id", class="habit_form habit_form_font">
                <option value=""><%= habit.title %></option>
                <% @my_habits.each do |habit_select| %>
                <option value=<%= habit_select.id %>><%= habit_select.title %></option>
                <% end %>
            </select>
            <% elsif %>
              <div class='habit_form'>
              <%= habit.title %>
              </div>
            <% end %>
            </div>
          </div>
          <div class='habit_list_right_btn'>
          <% if current_user.id == habit.user_id %>
            <div class='habit_list_edit_delete'>
              <%= f.submit "変更" ,class: "habit_edit_delete_btn message_habit_btn" %>
            </div>
            <%= link_to new_habit_path, class: "link" do %>
            <div class='habit_list_edit_delete'>
              <div class='message_habit_resist_btn'>
              登録
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
        </div>
          <div class='habit_list_bottom'>
            <ul>
            <li class='habit_item'><%= habit.item1 %></li>
            <li class='habit_item'><%= habit.item2 %></li>
            <li class='habit_item'><%= habit.item3 %></li>
            <li class='habit_item'><%= habit.item4 %></li>
            <li class='habit_item'><%= habit.item5 %></li>
            </ul>
          </div>
      <% end %>
      </div>
  </div>
  <% end %>

  <% if @not_habits != nil %>
    <% @not_habits.each do |not_habit| %>
      <div class='room_habit_list'>
          <div class='room_list_bottom'>
            <div class='message_user_name'>
            <%= not_habit.nickname %>
            </div>
          </div>
          <div class='habit_list' >
          <%= form_with model: @room, url: habit_add_room_path(@room.id), method: :post, local: true do |f| %>
            <div class='habit_list_top'>
              <div class='habit_list_left_btn'>
                <div class='habit_title'>
                <% if current_user.id == not_habit.id %>
                <select name="select_habit_id", class="habit_form habit_not_form_font">
                    <option value="">タイトルを選択して下さい。</option>
                    <% @my_habits.each do |habit_select| %>
                    <option value=<%= habit_select.id %>><%= habit_select.title %></option>
                    <% end %>
                </select>
                <% elsif %>
                  <div class='habit_form'>
                  未登録
                  </div>
                <% end %>
                </div>
              </div>
              <div class='habit_list_right_btn'>
              <% if current_user.id == not_habit.id %>
                <div class='habit_list_edit_delete'>
                  <%= f.submit "反映" ,class: "habit_edit_delete_btn message_habit_btn" %>
                </div>
                <%= link_to new_habit_path, class: "link" do %>
                <div class='habit_list_edit_delete'>
                  <div class='message_habit_resist_btn'>
                  登録
                  </div>
                </div>
                <% end %>
                <% end %>
              </div>
            </div>
              <div class='habit_list_bottom not_habit_item'>
              <div class='not_habit_list'>
              未登録
              </div>
              </div>
          <% end %>
          </div>
      </div>
    <% end %>
  <% end %>


</div>
<div class='message_middle'>
  <%= render partial: 'message', collection: @messages %>
</div>
<div class='message_bottom'>
  <div class='message_input'>
    <%= form_with model: [@room, @message],local: true do |f| %>
    <div class='message_form'>
    <%= f.text_field :comment, class: 'comment_form' %>
    </div>
    <%= f.submit 'SEND', class: 'message_send' %>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<%# CSS・・・assets/stylesheets/room.css %>
<%= render "share/header" %>
<div class='room-main'>
  <div class='room-detail'>

    <% current_user.rooms.each do |room| %>
    <div class='room-set'>
      <%= link_to room_messages_path(room), class: "link" do %>
      <div class='room-set-name'>
        <div class='room-name'><%= room.name %></div>
      </div>
      <% end %>
      <div class='room-set-member'>
        <div class='room-member'>
        <% room.users.where.not(id: current_user.id).each do |user| %>
        <div>
        <%= user.nickname %>
        </div>
        <% end %>
        </div>
      </div>
      <div class='room-set-delete'>
        <%= link_to room_path(room), method: :delete, class: "link" do %>
        <div class='room-delete'>削除</div>
        <% end %>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/rooms/new.html.erb
<%# CSS・・・assets/stylesheets/inputform.css %>
<%= render "share/header" %>
<div class='main_account'>
  <div>
    <div class='room-error'>
    <%# エラーメッセージを記述する %>
    </div>
      <div class='detail_new_room'>
        <div class='new_room_side'>
          <div class='room_create'>グループ作成</div>
        </div>
        <div class='new_room_main'>
          <%= form_with model: @room, url: rooms_path, local: true do |f| %>
          <div class='room_input'>
            <div class="field">
            <div>グループ名</div>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "グループ名を入力してください",class: "input_form" %>
            </div>
          </div>
          <div class='room_input'>
            <div class="field">
            <div>メンバー</div>
            <select name="room[user_ids][]", class="input_form">
              <option value="">ユーザを選択してください</option>
                <% User.where.not(id: current_user.id).each do |user| %>
                <option value=<%= user.id %>><%= user.nickname %></option>
                <% end %>
            </select>
            <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
            </div>
          </div>
            <%= f.submit "作成" ,class: "room_btn" %>
          </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/share/_header.html.erb
<%# CSS・・・assets/stylesheets/share/header.css %>
<header class='header'>
  <div class='title'>
    <%= link_to root_path , class: "link" do %>
      <div>Habit Maker</div>
    <% end %>
  </div>
  <% if user_signed_in? %>
  <div class='select'>
      <div class='user-nickname'>
      <%= link_to current_user.nickname, users_path , class: 'link' %>
      </div>
      <div class='new_room'>
      <%= link_to 'グループ作成', new_room_path , class: 'link' %>
      </div>
      <div class='logout'>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete , class: 'link' %>
      </div>
  </div>
  <% end %>
</header>

app/views/users/_list.html.erb
<div class='habit_list user_habit_list'>
  <div class='habit_list_top'>
    <div class='habit_list_left_btn'>
      <div class='habit_title'>
      <%= list.title %>
      </div>
    </div>
    <div class='habit_list_right_btn'>
      <%= link_to edit_habit_path(list.id),  class: "link" do %>
      <div class='habit_list_edit_delete'>
        <div class='habit_edit_delete_btn'>
        編集
        </div>
      </div>
      <% end %>
      <%= link_to habit_path(list.id), method: :delete,  class: "link" do %>
      <div class='habit_list_edit_delete'>
        <div class='habit_edit_delete_btn'>
        削除
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class='habit_list_bottom'>
  <ul>
  <li class='habit_item'><%= list.item1 %></li>
  <li class='habit_item'><%= list.item2 %></li>
  <li class='habit_item'><%= list.item3 %></li>
  <li class='habit_item'><%= list.item4 %></li>
  <li class='habit_item'><%= list.item5 %></li>
  </ul>
  </div>
</div>

app/views/users/index.html.erb
<%# CSS・・・assets/stylesheets/user.css %>
<%= render "share/header" %>
<div class='main_user'>
  <div class='center_user'>
    <div class='top_user'>
      <div class='top_user_name'>
        <div class='left_user_name'>
        ユーザー名 :
        </div>
        <div class='right_user_name'>
        <%= current_user.nickname %>
        </div>
      </div>
    </div>
    <div class='bottom_user'>
      <div class='user_habit_resist'>
        <%= link_to new_habit_path, class: "link" do %>
        <div class='resist_btn'>
        登録
        </div>
        <% end %>
        <div class='resist_comment'>
        : 習慣、目標を登録して下さい。
        </div>
      </div>
       <%# CSS・・・assets/stylesheets/user.css %>
      <div class='user_habit_lists'>
        <%= render partial: 'list', collection: @habits %>
      </div>
    </div>
  </div>
</div>